import Link from "next/link";
import { Bot } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Agent Analytics",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="fixed top-0 z-50 w-full border-b border-gray-200 bg-white/80 backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-emerald-600" />
            <span className="font-semibold">Agent Analytics</span>
          </Link>
          <Link
            href="/login"
            className="text-sm text-gray-500 transition-colors hover:text-gray-900"
          >
            Sign in
          </Link>
        </div>
      </nav>

      <article className="prose prose-gray mx-auto max-w-3xl px-6 pb-24 pt-28">
        <h1>Agent Analytics Terms of Service</h1>
        <p><strong>Last Updated: 2026/02/25</strong></p>

        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern access to and use of Agent Analytics
          (&ldquo;Agent Analytics,&rdquo; the &ldquo;Service&rdquo;), a free analytics tool provided by Pacific
          Intelligence Works, Inc. d/b/a Unusual (&ldquo;Unusual,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;). By accessing or using the Service, you (&ldquo;User,&rdquo; &ldquo;you&rdquo;) agree
          to these Terms. If you do not agree, do not use the Service.
        </p>

        <h2>1) The Service</h2>

        <h3>1.1 Overview</h3>
        <p>
          Agent Analytics is a free, open-source tool that monitors and reports on AI agent and
          crawler traffic to your website(s). The Service identifies visits from AI agents (e.g.,
          GPTBot, ClaudeBot, PerplexityBot), displays traffic volume, frequency, page-level
          breakdowns, and related analytics (&ldquo;Analytics Data&rdquo;).
        </p>

        <h3>1.2 Definitions</h3>
        <p>
          <strong>&ldquo;Analytics Data&rdquo;</strong> means the traffic data, metrics, and reports generated by the
          Service about AI agent activity on your website(s), including request counts, agent
          identifiers, crawled page paths, data transfer volumes, and timestamps.
        </p>
        <p>
          <strong>&ldquo;Connection Data&rdquo;</strong> means credentials, API keys, tokens, or other information you
          provide to connect the Service to your infrastructure provider(s) (e.g., Cloudflare).
        </p>
        <p>
          <strong>&ldquo;Service Data&rdquo;</strong> means data generated through your interaction with the Service,
          including usage logs, feature interaction data, session analytics, performance metrics,
          and technical diagnostics. Service Data does not include the substance of Analytics Data
          but may include metadata about its creation and use.
        </p>
        <p>
          <strong>&ldquo;Aggregated Data&rdquo;</strong> means data derived from Analytics Data or Service Data that has
          been aggregated, anonymized, or de-identified such that it does not identify you, your
          website(s), or any individual.
        </p>

        <h3>1.3 Free Service; No SLA</h3>
        <p>
          Agent Analytics is provided free of charge. We do not guarantee uptime, availability,
          accuracy, or completeness of Analytics Data. We may modify, suspend, or discontinue the
          Service (or any feature) at any time without notice or liability.
        </p>

        <h3>1.4 Open Source</h3>
        <p>
          Portions of Agent Analytics are released under an open-source license. The applicable
          license governs your use of the source code. These Terms govern your use of the hosted
          Service at analytics.unusual.ai.
        </p>

        <h2>2) Accounts &amp; Access</h2>

        <h3>2.1 Registration</h3>
        <p>
          You must provide accurate account information and maintain the security of your
          credentials. You are responsible for all activities under your account.
        </p>

        <h3>2.2 Eligibility</h3>
        <p>
          You must be at least 18 years old or the age of majority in your jurisdiction.
        </p>

        <h3>2.3 Connection to Infrastructure Providers</h3>
        <p>
          The Service may require you to connect your account to third-party infrastructure
          providers (e.g., Cloudflare). You are responsible for ensuring you have the right to
          grant the Service access to the relevant data from those providers. Use of third-party
          services is subject to their respective terms.
        </p>

        <h2>3) Data Rights</h2>

        <h3>3.1 Ownership</h3>
        <p>
          <strong>(a) Analytics Data.</strong> As between the parties, you retain all right, title,
          and interest in Analytics Data generated from your website(s).
        </p>
        <p>
          <strong>(b) Service Data.</strong> As between the parties, Unusual owns all Service Data.
        </p>
        <p>
          <strong>(c) Aggregated Data.</strong> As between the parties, Unusual owns all Aggregated Data.
        </p>
        <p>
          <strong>(d) The Service.</strong> Unusual and its licensors own all right, title, and
          interest in and to the Service and all related intellectual property (including software,
          documentation, algorithms, platform, architecture, know-how, trademarks, copyrights,
          patents, trade secrets, and all other intellectual property rights), excluding any
          open-source components governed by their respective licenses. Nothing in these Terms
          transfers any ownership rights in the Service to you.
        </p>

        <h3>3.2 License to Unusual</h3>
        <p>
          You grant Unusual a worldwide, non-exclusive, royalty-free license to access, process,
          and display Analytics Data and Connection Data to: (a) operate, maintain, secure, and
          deliver the Service; and (b) as otherwise permitted in these Terms (including Sections
          3.3 and 3.5).
        </p>

        <h3>3.3 Platform Improvement and Data Usage Rights</h3>
        <p>
          In addition to the license granted in Section 3.2, you grant Unusual a worldwide,
          non-exclusive, royalty-free license to:
        </p>
        <p>
          <strong>(a) Service Improvement.</strong> Use Analytics Data, Service Data, and Aggregated
          Data to develop, improve, and enhance the Service and Unusual&apos;s other products and
          services;
        </p>
        <p>
          <strong>(b) Aggregated Data.</strong> Aggregate, anonymize, or de-identify Analytics Data
          and Service Data to create Aggregated Data. Unusual may use, disclose, license, and
          exploit Aggregated Data for any lawful purpose without restriction, including product
          development, benchmarking, research, marketing, and commercial purposes.
        </p>

        <h3>3.4 Safeguards</h3>
        <p>
          Unusual will not make your Analytics Data directly available to any other user in
          identifiable form without your permission.
        </p>

        <h3>3.5 Marketing Communications</h3>
        <p>
          You acknowledge that Agent Analytics is provided by Unusual and that Unusual may use your
          account information (including name, email, and company) and Analytics Data to contact
          you about Unusual&apos;s other products and services. You may opt out of such
          communications at any time.
        </p>

        <h2>4) Acceptable Use</h2>
        <p>
          You will not: (a) violate any applicable law; (b) use the Service to monitor websites
          you do not own or have authorization to monitor; (c) submit malware or harmful code; (d)
          attempt unauthorized access to the Service or its infrastructure; (e) circumvent
          technical controls; (f) use scraping, data harvesting, or automated tools against the
          Service except as expressly allowed; or (g) interfere with or disrupt the Service or the
          experience of other users.
        </p>

        <h2>5) Disclaimers</h2>

        <h3>5.1 As-Is</h3>
        <p>
          THE SERVICE AND ALL ANALYTICS DATA ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE.&rdquo; UNUSUAL DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES
          ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.
        </p>

        <h3>5.2 Accuracy</h3>
        <p>
          Analytics Data depends on data from third-party infrastructure providers and the behavior
          of third-party AI agents. We do not warrant the accuracy, completeness, or timeliness of
          Analytics Data. AI agents may not consistently identify themselves, and traffic patterns
          may change without notice.
        </p>

        <h3>5.3 No Professional Advice</h3>
        <p>
          The Service and Analytics Data are for informational purposes only and do not constitute
          professional, legal, or business advice.
        </p>

        <h2>6) Limits of Liability</h2>

        <h3>6.1 Types of Damages</h3>
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW, UNUSUAL IS NOT LIABLE FOR INDIRECT, SPECIAL,
          INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES (INCLUDING LOST PROFITS,
          REVENUE, SAVINGS, OR DATA), EVEN IF ADVISED OF THE POSSIBILITY.
        </p>

        <h3>6.2 Cap</h3>
        <p>
          UNUSUAL&apos;S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THE SERVICE IS LIMITED TO
          ONE HUNDRED U.S. DOLLARS ($100).
        </p>

        <h3>6.3 Essential Basis</h3>
        <p>
          THE LIMITATIONS IN THIS SECTION 6 APPLY REGARDLESS OF THE FORM OF ACTION AND REFLECT AN
          ALLOCATION OF RISK THAT IS AN ESSENTIAL BASIS OF THESE TERMS.
        </p>

        <h2>7) Indemnification</h2>
        <p>
          You will defend, indemnify, and hold harmless Unusual and its affiliates, officers,
          directors, and employees from and against third-party claims, damages, liabilities,
          costs, and expenses (including reasonable attorneys&apos; fees) arising from: (a) your use
          of the Service; (b) your breach of these Terms; or (c) your violation of any applicable
          law.
        </p>

        <h2>8) Privacy</h2>
        <p>
          Our{" "}
          <Link href="/legal/privacy-policy" className="text-emerald-600 hover:text-emerald-700">
            Privacy Policy
          </Link>{" "}
          describes how we handle personal information in connection with the Service and is
          incorporated into these Terms.
        </p>

        <h2>9) Suspension &amp; Termination</h2>

        <h3>9.1 Suspension</h3>
        <p>
          We may suspend or terminate your access to the Service at any time, for any reason, with
          or without notice.
        </p>

        <h3>9.2 Termination by You</h3>
        <p>You may stop using the Service and delete your account at any time.</p>

        <h3>9.3 Effect of Termination</h3>
        <p>
          Upon termination, your right to access the Service ceases. We may delete your Analytics
          Data and Connection Data from active systems within a commercially reasonable period.
        </p>

        <h3>9.4 Survival</h3>
        <p>
          The following provisions survive termination: Sections 3.1 (Ownership), 3.3 (Platform
          Improvement and Data Usage Rights), 3.4 (Safeguards), 5 (Disclaimers), 6 (Limits of
          Liability), 7 (Indemnification), 10 (Dispute Resolution), and any other provisions which
          by their nature should survive.
        </p>

        <h2>10) Dispute Resolution; Governing Law</h2>

        <h3>10.1 Informal Resolution</h3>
        <p>
          Before filing any claim, you will confer with us in good faith for 30 days after written
          notice (email sufficient) to attempt to resolve the dispute.
        </p>

        <h3>10.2 Arbitration</h3>
        <p>
          Except for claims seeking injunctive relief to protect intellectual property rights, or
          claims brought in small claims court, any dispute arising out of or relating to these
          Terms or the Service will be resolved exclusively by binding arbitration administered by
          the American Arbitration Association (&ldquo;AAA&rdquo;) under its Commercial Arbitration
          Rules before a single arbitrator in Wilmington, Delaware, applying Delaware substantive
          law (without regard to conflicts of law principles). The Federal Arbitration Act governs
          this provision. All claims must be brought only in an individual capacity, and not as a
          plaintiff or class member in any purported class, collective, or representative action.
          The parties agree to keep the existence, content, and outcome of any arbitration
          confidential except as necessary to enforce the award or as required by law.
        </p>

        <h3>10.3 Severability</h3>
        <p>
          If any portion of this Section 10 is found unenforceable, that portion will be severed
          and the remainder enforced to the fullest extent permitted by law.
        </p>

        <h2>11) General</h2>

        <h3>11.1 Assignment</h3>
        <p>
          You may not assign these Terms without our prior written consent. We may assign these
          Terms to an affiliate or in connection with a merger, acquisition, or sale of
          substantially all assets.
        </p>

        <h3>11.2 Notices</h3>
        <p>
          Notices to Unusual must be sent to founders@unusual.ai. We may provide notices to the
          email associated with your account.
        </p>

        <h3>11.3 Entire Agreement</h3>
        <p>
          These Terms, together with the Privacy Policy, constitute the entire agreement between
          you and Unusual regarding Agent Analytics.
        </p>

        <h3>11.4 Waiver; Severability</h3>
        <p>
          Failure to enforce any provision is not a waiver. If any provision is unenforceable, the
          remainder remains in effect.
        </p>

        <h3>11.5 Attorneys&apos; Fees</h3>
        <p>
          In any legal action or proceeding to enforce rights under these Terms, the prevailing
          party shall be entitled to recover its reasonable attorneys&apos; fees, costs, and
          expenses.
        </p>

        <h2>12) Contact</h2>
        <p>
          Pacific Intelligence Works, Inc. d/b/a Unusual<br />
          San Francisco, CA<br />
          founders@unusual.ai
        </p>
      </article>
    </div>
  );
}
